USE [master]
GO
CREATE DATABASE [2faTest]
 CONTAINMENT = NONE
GO
ALTER DATABASE [2faTest] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [2faTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [2faTest] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [2faTest] SET ANSI_NULLS OFF
GO
ALTER DATABASE [2faTest] SET ANSI_PADDING OFF
GO
ALTER DATABASE [2faTest] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [2faTest] SET ARITHABORT OFF
GO
ALTER DATABASE [2faTest] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [2faTest] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [2faTest] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [2faTest] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [2faTest] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [2faTest] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [2faTest] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [2faTest] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [2faTest] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [2faTest] SET  DISABLE_BROKER
GO
ALTER DATABASE [2faTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [2faTest] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [2faTest] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [2faTest] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [2faTest] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [2faTest] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [2faTest] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [2faTest] SET RECOVERY SIMPLE
GO
ALTER DATABASE [2faTest] SET  MULTI_USER
GO
ALTER DATABASE [2faTest] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [2faTest] SET DB_CHAINING OFF
GO
ALTER DATABASE [2faTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [2faTest] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [2faTest] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [2faTest] SET QUERY_STORE = OFF
GO
USE [2faTest]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [2faTest]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUsers](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[otp] [varchar](255) NULL,
	[firstname] [varchar](50) NULL,
	[lastname] [varchar](50) NULL,
	[active] [bit] NOT NULL,
 CONSTRAINT [PK_tblUsers] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[tblUsers] ADD  CONSTRAINT [DF_tblUsers_active]  DEFAULT ((1)) FOR [active]
GO

USE [master]
GO
ALTER DATABASE [2faTest] SET  READ_WRITE
GO

/****** Insert default admin account user:'admin@default.local' password:'password' ******/
USE [2faTest]
GO
INSERT INTO [dbo].[tblUsers] (email, password, otp, firstname, lastname, active)
VALUES ('admin@default.local', '$2a$10$rAoh7GUjmB/YqpniZt6CIOcyl8O5vzvaMj/fWxh1oIRy1lg.2ZFRe', null, 'admin', 'admin', 1)
GO